name: GUI CI in Docker with Chrome 138

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISPLAY: :99
      SEED: ${{ secrets.SEED_PHRASE }}
      PASS: ${{ secrets.PASSWORD }}
      PIN: ${{ secrets.PIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Docker image
        run: docker build -t ci-chrome138:latest .

      - name: Run UI tests inside Docker
        run: |
          docker run --rm \
            -e DISPLAY=$DISPLAY \
            -e SEED="$SEED" \
            -e PASS="$PASS" \
            -e PIN="$PIN" \
            -v ${{ github.workspace }}:/workspace \
            -v ~/.m2:/root/.m2 \
            ci-chrome138:latest \
            bash /workspace/run-tests.sh

      - name: Upload screen recording
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screen-recording
          path: target/allure-results/screen_recording.mp4

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
