name: GUI CI with Chrome 138 in Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISPLAY: :99
      SEED: ${{ secrets.SEED_PHRASE }}
      PASS: ${{ secrets.PASSWORD }}
      PIN: ${{ secrets.PIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Строим Docker-образ прямо в CI
      - name: Build Docker image
        run: |
          docker build -t ci-chrome138 -f Dockerfile.ci .

      # Запускаем контейнер и тесты
      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -e DISPLAY=$DISPLAY \
            -e SEED="$SEED" \
            -e PASS="$PASS" \
            -e PIN="$PIN" \
            -v ${{ github.workspace }}:/workspace \
            ci-chrome138 \
            bash -c "
              cd /workspace && \
              echo 'Запускаем Xvfb...' && \
              Xvfb :99 -screen 0 1366x768x24 & sleep 3 && \
              echo 'Старт записи экрана...' && \
              ffmpeg -y -video_size 1366x768 -framerate 15 -f x11grab -i :99 \
                -codec:v libx264 -pix_fmt yuv420p screen_recording.mp4 > /dev/null 2>&1 & echo \$! > ffmpeg_pid.txt && \
              echo 'Запуск UI тестов...' && \
              mvn clean test \
                -DsuiteXmlFile='src/test/resources/StartSwap.xml' \
                -DSEED_PHRASE=\$SEED -DPASSWORD=\$PASS -DPIN=\$PIN ; \
              echo 'Остановка записи...' && \
              kill -INT \$(cat ffmpeg_pid.txt) && sleep 2 && \
              mkdir -p target/allure-results && cp screen_recording.mp4 target/allure-results/
            "

      # Загружаем видео как артефакт
      - name: Upload screen recording
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screen-recording
          path: screen_recording.mp4

      # История allure из gh-pages
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Генерация отчета allure
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      # Деплой отчета в gh-pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
